parameters:
    hostname: '%env(HOSTNAME)%'
    ocr_api_key: '%env(OCR_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $hostname: '%hostname%'
            $ocrApiKey: '%ocr_api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Api\Controller\:
        resource: '../src/Api/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Subscriber\ProductSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Subscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Subscriber\FridgeSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Subscriber\ExpirationDateNotificationSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\Decorator\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
